export const BUSINESS_GRAPH_UI_INVENTORY = Object.freeze({
  shell: [
    'scope-trigger',
    'refresh',
    'create',
    'retry',
    'choose-workspace',
    'board-project',
    'board-assignee',
    'board-group',
    'board-sort',
    'board-priority',
    'board-columns',
    'undo-delete',
    'undo-close-issues',
    'dismiss-close-undo',
    'work-show-closed',
    'work-show-empty-projects',
  ],
  noteLinks: ['note-insert-link', 'note-links-retry', 'note-links-toggle', 'note-backlinks-toggle'],
  emptyStates: [
    'board-empty-create',
    'list-empty-create',
    'timeline-empty-create',
  ],
  create: [
    'create-close',
    'create-kind',
    'create-scope',
    'create-title',
    'create-status',
    'create-priority',
    'create-toggle-context',
    'create-summary',
    'create-tags',
    'create-working-note',
    'create-another',
    'create-cancel',
    'create-submit',
  ],
  details: [
    'entry-properties',
    'entry-add-relation',
    'entry-cancel-relation',
    'entry-project-overview',
    'entry-waiting-extra',
    'entry-open-project',
    'entry-open-owner',
    'focus-more',
    'focus-title',
    'focus-status',
    'focus-priority',
    'focus-project',
    'focus-assignee',
    'focus-summary',
    'focus-connection-relation',
    'focus-connection-target',
    'focus-connection-add',
    'focus-working-note',
    'focus-due',
    'focus-reminder',
    'focus-waiting',
    'focus-snooze',
    'focus-tags',
    'focus-deliverables',
    'focus-delete',
    'focus-next-action',
    'focus-record-decision',
    'focus-save',
  ],
  datePicker: [
    'date-previous-month',
    'date-next-month',
    'date-clear',
    'date-today',
  ],
  confirm: [
    'confirm-close',
    'confirm-cancel',
    'confirm-submit',
  ],
  filters: [
    'filters-trigger',
    'display-trigger',
    'board-project-filter-clear',
    'board-assignee-filter-clear',
    'board-priority-filter-clear',
    'board-columns-expand-all',
    'all-kind',
    'all-kind-filter-clear',
  ],
  dispatch: [
    'dispatch',
  ],
  summary: [
    'changes-summarise',
    'summary-close',
    'summary-agent',
    'summary-since',
    'summary-instructions',
    'summary-cancel',
    'summary-start',
  ],
})

export const BUSINESS_GRAPH_DYNAMIC_CONTROL_PREFIXES = Object.freeze([
  'section-',
  'view-',
  'scope-',
  'board-column-',
  'board-expand-',
  'board-add-',
  'board-empty-',
  'card-priority-',
  'card-status-',
  'card-due-',
  'list-open-',
  'timeline-open-',
  'relationship-',
  'note-link-',
  'note-backlink-',
  'focus-related-',
  'focus-connection-remove-',
  'focus-activity-',
  'focus-file-',
  'focus-history-',
  'focus-meeting-person-remove-',
  'entry-open-person-',
])

export const BUSINESS_GRAPH_SURFACES = Object.freeze([
  'BusinessGraphApp.vue',
  '../../../shared/ui/DatePicker.vue',
  'DispatchBar.vue',
  'EntityList.vue',
  'GraphAppFeedback.vue',
  'GraphAppHeader.vue',
  'GraphCheckbox.vue',
  'GraphConfirmDialog.vue',
  'GraphCreateDialog.vue',
  'GraphDatePicker.vue',
  'GraphDateTimeField.vue',
  'GraphInspector.vue',
  'GraphEntryDetails.vue',
  'GraphMarkdownEditor.vue',
  'GraphRelationshipLine.vue',
  'GraphReferences.vue',
  'GraphSelect.vue',
  'GraphSummaryDialog.vue',
  'GraphViewbar.vue',
  'GraphWorkspace.vue',
  'NowView.vue',
  'ProjectStanding.vue',
  'TimelineView.vue',
  'WorkBoard.vue',
])
