export const BUSINESS_GRAPH_UI_INVENTORY = Object.freeze({
  shell: [
    'scope-trigger',
    'refresh',
    'create',
    'retry',
    'choose-workspace',
    'board-group',
    'board-sort',
    'board-priority',
    'board-columns',
    'undo-delete',
  ],
  emptyStates: [
    'board-empty-create',
    'list-empty-create',
    'portfolio-empty-create',
    'timeline-empty-create',
  ],
  create: [
    'create-close',
    'create-kind',
    'create-scope',
    'create-title',
    'create-status',
    'create-priority',
    'create-toggle-context',
    'create-summary',
    'create-tags',
    'create-working-note',
    'create-another',
    'create-cancel',
    'create-submit',
  ],
  peek: [
    'peek-history-back',
    'peek-history-forward',
    'peek-source',
    'peek-close',
    'peek-title',
    'peek-summary',
    'peek-status',
    'peek-priority',
    'peek-project',
    'peek-assignee',
    'peek-due',
    'peek-waiting',
    'peek-working-note',
    'peek-focus',
    'peek-more',
    'peek-next-action',
    'peek-record-decision',
    'peek-details',
    'peek-delete',
  ],
  focus: [
    'focus-back',
    'focus-history-back',
    'focus-history-forward',
    'focus-source',
    'focus-more',
    'focus-close',
    'focus-title',
    'focus-status',
    'focus-priority',
    'focus-project',
    'focus-assignee',
    'focus-summary',
    'focus-connection-relation',
    'focus-connection-target',
    'focus-connection-add',
    'focus-working-note',
    'focus-due',
    'focus-reminder',
    'focus-waiting',
    'focus-snooze',
    'focus-tags',
    'focus-deliverables',
    'focus-delete',
    'focus-next-action',
    'focus-record-decision',
    'focus-save',
  ],
  datePicker: [
    'date-previous-month',
    'date-next-month',
    'date-clear',
    'date-today',
  ],
  confirm: [
    'confirm-close',
    'confirm-cancel',
    'confirm-submit',
  ],
  filters: [
    'board-priority-filter-clear',
    'board-columns-filter-clear',
    'all-kind',
    'all-kind-filter-clear',
  ],
  dispatch: [
    'dispatch',
  ],
  summary: [
    'changes-summarise',
    'summary-close',
    'summary-agent',
    'summary-since',
    'summary-instructions',
    'summary-cancel',
    'summary-start',
  ],
})

export const BUSINESS_GRAPH_DYNAMIC_CONTROL_PREFIXES = Object.freeze([
  'section-',
  'view-',
  'scope-',
  'board-column-',
  'board-add-',
  'board-empty-',
  'card-priority-',
  'card-status-',
  'card-due-',
  'list-open-',
  'portfolio-open-',
  'timeline-open-',
  'relationship-',
  'peek-activity-',
  'peek-deliverable-',
  'focus-related-',
  'focus-connection-remove-',
  'focus-activity-',
  'focus-deliverable-',
])

export const BUSINESS_GRAPH_SURFACES = Object.freeze([
  'BusinessGraphApp.vue',
  '../../../shared/ui/DatePicker.vue',
  'DispatchBar.vue',
  'EntityList.vue',
  'GraphCheckbox.vue',
  'GraphConfirmDialog.vue',
  'GraphCreateDialog.vue',
  'GraphDatePicker.vue',
  'GraphDateTimeField.vue',
  'GraphInspector.vue',
  'GraphMarkdownEditor.vue',
  'GraphRelationshipLine.vue',
  'GraphSelect.vue',
  'GraphSummaryDialog.vue',
  'NowView.vue',
  'PortfolioView.vue',
  'ProjectStanding.vue',
  'TimelineView.vue',
  'WorkBoard.vue',
])
